-   name: train_tensorflow_linear_test
    cluster:
        app_config: app_config.yaml
        compute_template: compute_tpl.yaml

    run:
        use_connect: True
        autosuspend_mins: 20
        timeout: 36000
        script: python workloads/train_tensorflow_linear_test.py

-   name: train_torch_linear_test
    cluster:
        app_config: app_config.yaml
        compute_template: compute_tpl.yaml

    run:
        use_connect: True
        autosuspend_mins: 20
        timeout: 36000
        script: python workloads/train_torch_linear_test.py
