base_image: "anyscale/ray-ml:pinned-nightly-py37-gpu"
env_vars: {}

debian_packages:
  - curl

python:
  conda_packages: []
  pip_packages:
    - filelock>=3.3.0

post_build_cmds:
  - pip uninstall -y numpy ray || true
  - sudo rm -rf /home/ray/anaconda3/lib/python3.7/site-packages/numpy
  - pip3 install numpy || true
  - pip3 install -U {{ env["RAY_WHEELS"] | default("ray") }}
  - pip3 install -U git+https://github.com/horovod/horovod.git
  - {{ env["RAY_WHEELS_SANITY_CHECK"] | default("echo No Ray wheels sanity check") }}
